### ISSUE TITLE
[Bug]: 208.67.222.222 is responding 404 which makes the package unreliable

### ISSUE THREAD

**Issue by totzk9** [Iteo/connecteo#55]
### Desctibe the bug

having internet connection but package will result a "no connection" because of a failure check of 208.67.222.222

### Reproduction steps

just the package as usual

### Expected behaviour

Should return true for `isConnected`

### Flutter version

latest

### Package version

3.0.0

### What platform are you seeing the problem on?

Android

### Relevant log output

```shell
no logs.
```

**Comment by tomkad99** [comment]
Hi @totzk9 

Thank you for the posted issue. I have checked the address `208.67.222.222` and after my ping it seems to be responding correctly. I also see that connecteo uses two other IPs as a backup.

Can you confirm this problem is still present on your side. Maybe you used VPN or other packets loss happened.

**Comment by totzk9** [comment]
Interesting. Had to review the package code and found `return connectionResults.any((result) => result);` which means it returns true if one of the three is reachable.

Apologies of my misunderstanding. Though what's weird is I still get a `false` value from the 3 IPs but returns `true` when checking for `baseUrlLookupAddress`

Anyway, we can close the issue. Thank you!

**Comment by tomkad99** [comment]
Okay. Thank you for quick recheck :) 
We will close this issue soon.
